context("SEMinR predicts PLSc models with the model-implied rule (#425)\n")

# Oracle: cSEM model-implied indicator correlations of the same PLSc model, turned
# into conditional expectations (de Rooij et al., 2023). Generated by
# fixtures/make_plsc_oracle.R; see that script for the designs.
oracle <- readRDS(test_path("fixtures", "plsc_oracle.rds"))
train <- mobi[1:200, ]
test  <- mobi[201:250, ]

reflective_two_mm <- constructs(
  reflective("Image",        multi_items("IMAG", 1:5)),
  reflective("Expectation",  multi_items("CUEX", 1:3)),
  reflective("Satisfaction", multi_items("CUSA", 1:3))
)
reflective_two_sm <- relationships(
  paths(from = c("Image", "Expectation"), to = "Satisfaction")
)
chain_mm <- constructs(
  reflective("Image",        multi_items("IMAG", 1:5)),
  reflective("Expectation",  multi_items("CUEX", 1:3)),
  reflective("Quality",      multi_items("PERQ", 1:7)),
  reflective("Satisfaction", multi_items("CUSA", 1:3))
)
chain_sm <- relationships(
  paths(from = "Image",       to = "Expectation"),
  paths(from = "Expectation", to = "Quality"),
  paths(from = c("Image", "Expectation", "Quality"), to = "Satisfaction")
)
mixed_mm <- constructs(
  reflective("Image",        multi_items("IMAG", 1:5)),
  composite("Value",         multi_items("PERV", 1:2), weights = mode_B),
  reflective("Satisfaction", multi_items("CUSA", 1:3))
)
mixed_sm <- relationships(
  paths(from = c("Image", "Value"), to = "Satisfaction")
)

expect_same_paths <- function(model, oracle_fit) {
  P <- oracle_fit$paths
  for (to in rownames(P)) for (from in colnames(P)) if (P[to, from] != 0)
    expect_equal(model$path_coef[from, to], P[to, from], tolerance = 1e-6)
}

test_that("PLSc item predictions equal the model-implied conditional expectation", {
  model <- suppressMessages(estimate_pls(train, reflective_two_mm, reflective_two_sm))
  expect_same_paths(model, oracle$reflective_two)
  pred <- predict(model, test, technique = predict_DA)$predicted_items
  y <- colnames(oracle$reflective_two$items)
  expect_equal(unname(as.matrix(pred[, y])), unname(oracle$reflective_two$items),
               tolerance = 1e-6)
})

test_that("PLSc predictions follow the DA and EA predictor sets in a non-saturated chain", {
  model <- suppressMessages(estimate_pls(train, chain_mm, chain_sm))
  expect_same_paths(model, oracle$chain_DA)
  for (tech in c("DA", "EA")) {
    o <- oracle[[paste0("chain_", tech)]]$items
    technique <- if (tech == "DA") predict_DA else predict_EA
    pred <- predict(model, test, technique = technique)$predicted_items
    expect_equal(unname(as.matrix(pred[, colnames(o)])), unname(o), tolerance = 1e-6,
                 info = tech)
  }
})

test_that("mixed reflective and Mode B composite models use observed within-block correlations", {
  model <- suppressMessages(estimate_pls(train, mixed_mm, mixed_sm))
  expect_same_paths(model, oracle$mixed)
  pred <- predict(model, test)$predicted_items
  o <- oracle$mixed$items
  expect_equal(unname(as.matrix(pred[, colnames(o)])), unname(o), tolerance = 1e-6)
})

test_that("Mode A composites in PLSc models are not disattenuated (rho = 1)", {
  mm <- constructs(
    reflective("Image",        multi_items("IMAG", 1:5)),
    composite("Quality",       multi_items("PERQ", 1:7)),
    composite("Value",         multi_items("PERV", 1:2), weights = mode_B),
    reflective("Satisfaction", multi_items("CUSA", 1:3))
  )
  sm <- relationships(
    paths(from = "Image", to = "Quality"),
    paths(from = c("Image", "Quality", "Value"), to = "Satisfaction")
  )
  model <- suppressMessages(estimate_pls(train, mm, sm))
  expect_same_paths(model, oracle$mixed_mode_A)
  pred <- predict(model, test)$predicted_items
  o <- oracle$mixed_mode_A$items
  expect_equal(unname(as.matrix(pred[, colnames(o)])), unname(o), tolerance = 1e-6)
})

test_that("single-item reflective constructs are predicted (and predict from) correctly", {
  mm <- constructs(
    reflective("Image",        multi_items("IMAG", 1:5)),
    reflective("Satisfaction", multi_items("CUSA", 1:3)),
    reflective("Complaints",   single_item("CUSCO"))
  )
  sm <- relationships(
    paths(from = "Image", to = "Satisfaction"),
    paths(from = "Satisfaction", to = "Complaints")
  )
  model <- suppressMessages(estimate_pls(train, mm, sm))
  expect_same_paths(model, oracle$single_item)
  pred <- predict(model, test)$predicted_items
  o <- oracle$single_item$items
  expect_equal(unname(as.matrix(pred[, colnames(o)])), unname(o), tolerance = 1e-6)
})

test_that("PLSc construct predictions are expected composite scores, in the metric of actual_star", {
  model <- suppressMessages(estimate_pls(train, reflective_two_mm, reflective_two_sm))
  p <- predict(model, test)
  y <- construct_items(model$mmMatrix, "Satisfaction")
  z_hat <- standardize_data(as.matrix(p$predicted_items[, y]),
                            model$meanData[y], model$sdData[y])
  expect_equal(unname(p$predicted_composite_scores[, "Satisfaction"]),
               unname(drop(z_hat %*% model$outer_weights[y, "Satisfaction"])),
               tolerance = 1e-10)
})

test_that("an inadmissible PLSc solution stops prediction instead of being repaired", {
  model <- suppressMessages(estimate_pls(train, reflective_two_mm, reflective_two_sm))
  model$outer_loadings["CUSA1", "Satisfaction"] <- 1.05
  expect_error(predict(model, test), "inadmissible.*CUSA1")
})

test_that("predict_pls() skips folds whose PLSc solution is inadmissible, with one warning", {
  # Full-sample chain model is admissible, but with seed 1 and 5 folds some
  # training folds give PLSc R^2 > 1 (cSEM agrees: inadmissible). Those folds
  # are skipped: their test rows are NA for PLS and LM alike, and the metrics
  # use the remaining rows. Never fall back to the PLS chain.
  model <- suppressMessages(estimate_pls(mobi, chain_mm, chain_sm))
  set.seed(1)
  expect_warning(
    cv <- predict_pls(model, technique = predict_DA, noFolds = 5),
    "inadmissible in [1-4] of 5 cross-validation folds"
  )
  expect_s3_class(cv, "predict_pls_model")
  oos <- cv$items$PLS_out_of_sample
  lm_oos <- cv$items$lm_out_of_sample
  skipped <- !stats::complete.cases(oos)
  expect_true(any(skipped) && !all(skipped))
  # PLS and LM are compared on the same rows
  expect_identical(skipped, !stats::complete.cases(lm_oos))
  metrics <- summary(cv)$PLS_out_of_sample
  expect_true(all(is.finite(metrics)))
})

test_that("an inadmissible fold does not leak a stray error inside an enclosing tryCatch", {
  model <- suppressMessages(estimate_pls(mobi, chain_mm, chain_sm))
  set.seed(1)
  res <- tryCatch(suppressWarnings(predict_pls(model, noFolds = 5)), error = identity)
  expect_s3_class(res, "predict_pls_model")
})

test_that("PLSc models with interactions are refused rather than predicted in mixed metrics", {
  mm <- constructs(
    reflective("Image",        multi_items("IMAG", 1:5)),
    reflective("Expectation",  multi_items("CUEX", 1:3)),
    reflective("Satisfaction", multi_items("CUSA", 1:3)),
    interaction_term(iv = "Image", moderator = "Expectation", method = two_stage)
  )
  sm <- relationships(
    paths(from = c("Image", "Expectation", "Image*Expectation"), to = "Satisfaction")
  )
  model <- suppressMessages(estimate_pls(train, mm, sm))
  expect_error(predict(model, test), "interaction terms.*issues/427")
  expect_error(predict_pls(model, noFolds = 5), "interaction terms.*issues/427")
  # predict_pls() stops before cross-validation, not from inside a fold
  err <- tryCatch(predict_pls(model, noFolds = 5), error = identity)
  expect_null(conditionCall(err))
})

test_that("predict_pls() runs cross-validation for PLSc models", {
  set.seed(425)
  model <- suppressMessages(estimate_pls(mobi, reflective_two_mm, reflective_two_sm))
  cv <- predict_pls(model, technique = predict_DA, noFolds = 5)
  expect_s3_class(cv, "predict_pls_model")
  expect_false(anyNA(cv$items$PLS_out_of_sample))
})

test_that("predict_pls() uses earliest antecedents for PLSc models with predict_EA", {
  model <- suppressMessages(estimate_pls(mobi, chain_mm, chain_sm))
  set.seed(425)
  cv_ea <- predict_pls(model, technique = predict_EA, noFolds = 5)
  set.seed(425)
  cv_da <- predict_pls(model, technique = predict_DA, noFolds = 5)
  expect_false(anyNA(cv_ea$items$PLS_out_of_sample))
  # Same folds; Quality and Satisfaction have predictors other than Image under DA
  expect_false(isTRUE(all.equal(cv_ea$items$PLS_out_of_sample, cv_da$items$PLS_out_of_sample)))
})

test_that("predict_pls() gives the same PLSc predictions in parallel workers", {
  # Workers load the installed seminr (run devtools::install() first). Kept small
  # and off CRAN: 2 cores, 4 folds.
  skip_on_cran()
  model <- suppressMessages(estimate_pls(mobi, chain_mm, chain_sm))
  set.seed(425)
  sequential <- predict_pls(model, technique = predict_EA, noFolds = 4)
  set.seed(425)
  parallel <- predict_pls(model, technique = predict_EA, noFolds = 4, cores = 2)
  expect_equal(parallel$items$PLS_out_of_sample, sequential$items$PLS_out_of_sample)
  expect_equal(parallel$items$PLS_in_sample, sequential$items$PLS_in_sample)
})

# Not tested: the "not positive definite" error for the predictor block in
# plsc_implied_predictions(). We have no realistic model that reaches it once the
# loading and implied construct correlation checks pass; it stays as a guard.

test_that("CB-SEM models get an informative error instead of the PLS prediction chain", {
  cb <- suppressMessages(estimate_cbsem(train, reflective_two_mm, reflective_two_sm))
  expect_error(predict(cb, test), "CB-SEM.*lavPredictY")
  expect_error(predict_pls(cb, noFolds = 5), "CB-SEM.*lavPredictY")
})

test_that("CFA models get an informative error instead of the PLS prediction chain", {
  cfa <- suppressMessages(estimate_cfa(train, reflective_two_mm))
  expect_error(predict(cfa, test), "CFA.*no structural model")
  expect_error(predict_pls(cfa, noFolds = 5), "CFA.*no structural model")
})
