context("SEMinR predicts PLSc models with the model-implied rule (#425)\n")

# Oracle: cSEM model-implied indicator correlations of the same PLSc model, turned
# into conditional expectations (de Rooij et al., 2023). Generated by
# fixtures/make_plsc_oracle.R; see that script for the designs.
oracle <- readRDS(test_path("fixtures", "plsc_oracle.rds"))
train <- mobi[1:200, ]
test  <- mobi[201:250, ]

reflective_two_mm <- constructs(
  reflective("Image",        multi_items("IMAG", 1:5)),
  reflective("Expectation",  multi_items("CUEX", 1:3)),
  reflective("Satisfaction", multi_items("CUSA", 1:3))
)
reflective_two_sm <- relationships(
  paths(from = c("Image", "Expectation"), to = "Satisfaction")
)
chain_mm <- constructs(
  reflective("Image",        multi_items("IMAG", 1:5)),
  reflective("Expectation",  multi_items("CUEX", 1:3)),
  reflective("Quality",      multi_items("PERQ", 1:7)),
  reflective("Satisfaction", multi_items("CUSA", 1:3))
)
chain_sm <- relationships(
  paths(from = "Image",       to = "Expectation"),
  paths(from = "Expectation", to = "Quality"),
  paths(from = c("Image", "Expectation", "Quality"), to = "Satisfaction")
)
mixed_mm <- constructs(
  reflective("Image",        multi_items("IMAG", 1:5)),
  composite("Value",         multi_items("PERV", 1:2), weights = mode_B),
  reflective("Satisfaction", multi_items("CUSA", 1:3))
)
mixed_sm <- relationships(
  paths(from = c("Image", "Value"), to = "Satisfaction")
)

expect_same_paths <- function(model, oracle_fit) {
  P <- oracle_fit$paths
  for (to in rownames(P)) for (from in colnames(P)) if (P[to, from] != 0)
    expect_equal(model$path_coef[from, to], P[to, from], tolerance = 1e-6)
}

test_that("PLSc item predictions equal the model-implied conditional expectation", {
  model <- suppressMessages(estimate_pls(train, reflective_two_mm, reflective_two_sm))
  expect_same_paths(model, oracle$reflective_two)
  pred <- predict(model, test, technique = predict_DA)$predicted_items
  y <- colnames(oracle$reflective_two$items)
  expect_equal(unname(as.matrix(pred[, y])), unname(oracle$reflective_two$items),
               tolerance = 1e-6)
})

test_that("PLSc predictions follow the DA and EA predictor sets in a non-saturated chain", {
  model <- suppressMessages(estimate_pls(train, chain_mm, chain_sm))
  expect_same_paths(model, oracle$chain_DA)
  for (tech in c("DA", "EA")) {
    o <- oracle[[paste0("chain_", tech)]]$items
    technique <- if (tech == "DA") predict_DA else predict_EA
    pred <- predict(model, test, technique = technique)$predicted_items
    expect_equal(unname(as.matrix(pred[, colnames(o)])), unname(o), tolerance = 1e-6,
                 info = tech)
  }
})

test_that("mixed reflective and Mode B composite models use observed within-block correlations", {
  model <- suppressMessages(estimate_pls(train, mixed_mm, mixed_sm))
  expect_same_paths(model, oracle$mixed)
  pred <- predict(model, test)$predicted_items
  o <- oracle$mixed$items
  expect_equal(unname(as.matrix(pred[, colnames(o)])), unname(o), tolerance = 1e-6)
})

test_that("single-item reflective constructs are predicted (and predict from) correctly", {
  mm <- constructs(
    reflective("Image",        multi_items("IMAG", 1:5)),
    reflective("Satisfaction", multi_items("CUSA", 1:3)),
    reflective("Complaints",   single_item("CUSCO"))
  )
  sm <- relationships(
    paths(from = "Image", to = "Satisfaction"),
    paths(from = "Satisfaction", to = "Complaints")
  )
  model <- suppressMessages(estimate_pls(train, mm, sm))
  expect_same_paths(model, oracle$single_item)
  pred <- predict(model, test)$predicted_items
  o <- oracle$single_item$items
  expect_equal(unname(as.matrix(pred[, colnames(o)])), unname(o), tolerance = 1e-6)
})

test_that("PLSc construct predictions are expected composite scores, in the metric of actual_star", {
  model <- suppressMessages(estimate_pls(train, reflective_two_mm, reflective_two_sm))
  p <- predict(model, test)
  y <- construct_items(model$mmMatrix, "Satisfaction")
  z_hat <- standardize_data(as.matrix(p$predicted_items[, y]),
                            model$meanData[y], model$sdData[y])
  expect_equal(unname(p$predicted_composite_scores[, "Satisfaction"]),
               unname(drop(z_hat %*% model$outer_weights[y, "Satisfaction"])),
               tolerance = 1e-10)
})

test_that("an inadmissible PLSc solution stops prediction instead of being repaired", {
  model <- suppressMessages(estimate_pls(train, reflective_two_mm, reflective_two_sm))
  model$outer_loadings["CUSA1", "Satisfaction"] <- 1.05
  expect_error(predict(model, test), "inadmissible.*CUSA1")
})

test_that("PLSc models with interactions are refused rather than predicted in mixed metrics", {
  mm <- constructs(
    reflective("Image",        multi_items("IMAG", 1:5)),
    reflective("Expectation",  multi_items("CUEX", 1:3)),
    reflective("Satisfaction", multi_items("CUSA", 1:3)),
    interaction_term(iv = "Image", moderator = "Expectation", method = two_stage)
  )
  sm <- relationships(
    paths(from = c("Image", "Expectation", "Image*Expectation"), to = "Satisfaction")
  )
  model <- suppressMessages(estimate_pls(train, mm, sm))
  expect_error(predict(model, test), "interaction")
})

test_that("predict_pls() runs cross-validation for PLSc models", {
  set.seed(425)
  model <- suppressMessages(estimate_pls(mobi, reflective_two_mm, reflective_two_sm))
  cv <- predict_pls(model, technique = predict_DA, noFolds = 5)
  expect_s3_class(cv, "predict_pls_model")
  expect_false(anyNA(cv$items$PLS_out_of_sample))
})

