#' Measurement functions
#'
#' \code{constructs} creates the factors from measurement items by assigning the
#' relevant items to each factor and specifying reflective or formative (composite/causal) measurement models
#'
#' This function conveniently maps measurement items to factors using
#' root name, numbers, and affixes with explicit definition of formative
#' or reflective relationships
#'
#' @param \code{vector} of latent variable measurement specifications, as generated by the \code{reflective()}, \code{causal()}, or \code{composite()}
#'
#' @usage
#'   measurement_model <- constructs(
#'                          reflective("Satisfaction", multi_items("SAT", 1:3)),
#'                          composite("Reputation", multi_items("REP", 1:3)),
#'                          causal("Performance", c("ROE", "ROA"))
#'                        )
#'
#' @seealso See \code{\link{causal}}, \code{\link{composite}}, \code{\link{reflective}}, \code{\link{multi_items}}
#'   and \code{\link{single_item}}
#'
#' @examples
#'   mobi_mm <- constructs(
#'     reflective("Image",        multi_items("IMAG", 1:5)),
#'     reflective("Expectation",  multi_items("CUEX", 1:3)),
#'     reflective("Quality",      multi_items("PERQ", 1:7)),
#'     reflective("Value",        multi_items("PERV", 1:2)),
#'     reflective("Satisfaction", multi_items("CUSA", 1:3)),
#'     reflective("Complaints",   single_item("CUSCO")),
#'     reflective("Loyalty",      multi_items("CUSL", 1:3))
#'   )
#' @export
constructs <- function(...) {
  return(matrix(c(...), ncol = 3, byrow = TRUE,
                dimnames = list(NULL, c("latent", "measurement", "type"))))
}

#' Reflective construct measurement model specification
#'
#' \code{reflective} creates the reflective measurement model matrix for a specific construct,
#' specifying the relevant items of the construct and assigning the relationship of reflective or Mode A.
#' By definition this construct will be estimated by PLS consistent.
#'
#' This function conveniently maps reflectively defined measurement items to a construct and is estimated
#' using PLS consistent.
#'
#' @param \code{construct_name} of construct
#' @param \code{item_names} returned by the \code{multi_items} or \code{single_item} functions
#'
#' @usage
#'   measurement_model <- constructs(
#'                          reflective("Satisfaction", multi_items("SAT", 1:3)),
#'                        )
#'
#' @seealso See \code{\link{composite}}, \code{\link{reflective}}, \code{\link{multi_items}}
#'   and \code{\link{single_item}}
#'
#' @examples
#'   mobi_mm <- constructs(
#'     reflective("Image",        multi_items("IMAG", 1:5)),
#'     reflective("Expectation",  multi_items("CUEX", 1:3)),
#'     reflective("Quality",      multi_items("PERQ", 1:7)),
#'     reflective("Value",        multi_items("PERV", 1:2)),
#'     reflective("Satisfaction", multi_items("CUSA", 1:3)),
#'     reflective("Complaints",   single_item("CUSCO")),
#'     reflective("Loyalty",      multi_items("CUSL", 1:3))
#'   )
#' @export
reflective <- function(construct_name, item_names) {
  construct_names <- rep(construct_name, length(item_names))
  return(c(rbind(construct_names, item_names, "C")))
}

###### Deprecate causal
# #' @export
# causal <- function(construct_name, item_names) {
#   construct_names <- rep(construct_name, length(item_names))
#   return(c(rbind(construct_names,item_names,"B")))
# }

#' Composite construct measurement model specification
#'
#' \code{composite} creates the composite measurement model matrix for a specific construct,
#' specifying the relevant items of the construct and assigning the relationship of either
#' correlation weights (Mode A) or regression weights (Mode B).
#'
#' This function conveniently maps composite defined measurement items to a construct and is
#' estimated using PLS.
#'
#' @param \code{construct_name} of construct
#' @param \code{item_names} returned by the \code{multi_items} or \code{single_item} functions
#' @param \code{weights} is the relationship between the construct and its items. This can be
#' specified as "correlation" or "A" for correlation weights(Mode A) or as "regression" or "B" for
#' regression weights(Mode B).
#'
#' @usage
#'   measurement_model <- constructs(
#'                          composite("Satisfaction", multi_items("SAT", 1:3), weights = "correlation"),
#'                        )
#'
#' @seealso See \code{\link{composite}}, \code{\link{reflective}}, \code{\link{multi_items}}
#'   and \code{\link{single_item}}
#'
#' @examples
#'   mobi_mm <- constructs(
#'     composite("Image",        multi_items("IMAG", 1:5), weights = "correlation"),
#'     composite("Expectation",  multi_items("CUEX", 1:3), weights = "A"),
#'     composite("Quality",      multi_items("PERQ", 1:7), weights = "regression"),
#'     composite("Value",        multi_items("PERV", 1:2), weights = "B")
#'   )
#' @export
composite <- function(construct_name, item_names, weights = "correlation") {
  construct_names <- rep(construct_name, length(item_names))
  if(weights == "correlation" | weights == "A") {
    return(c(rbind(construct_names,item_names,"A")))
  }
  if(weights == "regression" | weights == "B") {
    return(c(rbind(construct_names,item_names,"B")))
  }
}

# arguments:
#   item_name: root name of all items
#   item_numbers: vector of item numbers
#   ...: optional affix arguments
#     prefix: prefix before each item name
#     mid: insert between item name and numbers
#     suffix: suffix after each ite name
#
# e.g.> multi_items("item", 0:3, prefix="X_", mid=".", suffix="_")
#
#' @export
multi_items <- function(item_name, item_numbers, ...) {
  affix <- as.data.frame(list(...))
  paste(affix$prefix, item_name, affix$mid, item_numbers, affix$suffix, sep = "")
}

#' @export
single_item <- function(item) {
  return(item)
}
