#' seminr estimate_cbsem() function
#'
#' The \code{seminr} package provides a natural syntax for researchers to describe
#' structural equation models.
#'
#' @param data A \code{dataframe} containing the indicator measurement data.
#'
#' @param measurement_model A source-to-target matrix representing the outer/measurement model,
#'   generated by \code{constructs}. Note that only reflective constructs are supported.
#'
#' @param structural_model A source-to-target matrix representing the inner/structural model,
#'   generated by \code{relationships}.
#'
#' @usage
#' estimate_cbsem(data, measurement_model, structural_model)
#'
#' @seealso \code{\link{as.reflective}} \code{\link{all.reflective}}
#'          \code{\link{relationships}} \code{\link{constructs}}
#'          \code{\link{paths}} \code{\link{interaction_term}}
#'          \code{\link{bootstrap_model}}
#'
#' @examples
#' mobi <- mobi
#'
#' #seminr syntax for creating measurement model
#' mobi_mm <- constructs(
#'              reflective("Image",        multi_items("IMAG", 1:5)),
#'              reflective("Quality",      multi_items("PERQ", 1:7)),
#'              reflective("Value",        multi_items("PERV", 1:2)),
#'              reflective("Satisfaction", multi_items("CUSA", 1:3)),
#'              reflective("Complaints",   single_item("CUSCO")),
#'              reflective("Loyalty",      multi_items("CUSL", 1:3))
#'            )
#'
#' #seminr syntax for freeing up item-item covariances
#' mobi_am <- associations(
#'              item_errors(c("PERQ1", "PERQ2"), "IMAG1")
#'            )
#'
#' #seminr syntax for creating structural model
#' mobi_sm <- relationships(
#'   paths(from = c("Image", "Quality"), to = c("Value", "Satisfaction")),
#'   paths(from = c("Value", "Satisfaction"), to = c("Complaints", "Loyalty")),
#'   paths(from = "Complaints",   to = "Loyalty")
#' )
#'
#' # Estimate model and get results
#' mobi_cbsem <- estimate_cbsem(mobi, mobi_mm, mobi_sm, mobi_am)
#' summary(mobi_cbsem)
#' @export
estimate_cbsem <- function(data, measurement_model, structural_model, item_associations=NULL, estimator="MLR", ...) {
  cat("Generating the seminr model for CBSEM\n")

  # TODO: see if fiml and other imputations work
  # data <- stats::na.omit(data)

  # TODO: consider higher order models (see estimate_pls() function for template)

  # TODO: process interactions limited to repeated measures and orthogonalization
  post_interaction_object <- process_cbsem_interactions(measurement_model, data, structural_model, estimator=estimator, ...)
  names(post_interaction_object$data) <- sapply(names(post_interaction_object$data), FUN=lavaanify_name, USE.NAMES = FALSE)
  mmMatrix <- post_interaction_object$mmMatrix
  data <- post_interaction_object$data
  # mmMatrix <- mm2matrix(measurement_model)

  # Rename interaction terms
  structural_model[, "source"] <- sapply(structural_model[, "source"], FUN=lavaanify_name)
  smMatrix <- structural_model

  # TODO: warning if the model is incorrectly specified
  # warnings(measurement_model, data, structural_model)

  # Create LAVAAN syntax
  # measurement_syntax <- lavaan_mm_syntax(measurement_model) # TODO: interactions in lavaan syntax
  measurement_syntax <- lavaan_mm_syntax(mmMatrix) # TODO: interactions in lavaan syntax
  structural_syntax <- lavaan_sm_syntax(smMatrix)
  association_syntax <- lavaan_item_associations(item_associations)

  # Put all the parts together
  full_syntax <- paste(measurement_syntax, structural_syntax, association_syntax,
                       sep="\n\n")

  # Run the model in LAVAAN
  library(lavaan) # TODO: suppress and replace Lavaan startup message
  lavaan_model <- sem(model=full_syntax, data=data, std.lv = TRUE,
                      estimator=estimator, ...)

  # Inspect results
  constructs <- all_construct_names(measurement_model)
  # all_terms <- construct_names(smMatrix)
  lavaan_std <- lavaan::lavInspect(lavaan_model, what="std")
  loadings <- lavaan_std$lambda
  class(loadings) <- "matrix"

  # Gather model information
  seminr_model <- list(
    data = data,
    measurement_model = measurement_model,
    mmMatrix = mmMatrix,
    smMatrix = smMatrix,
    factor_loadings = loadings,
    associations = item_associations,
    constructs = constructs,
    # all_terms = all_terms,
    lavaan_syntax = full_syntax,
    lavaan_model = lavaan_model
  )

  class(seminr_model) <- c("cbsem_model", "seminr_model")
  return(seminr_model)
}

#' #' @examples
#' mobi <- mobi
#'
#' #seminr syntax for creating measurement model
#' mobi_mm <- constructs(
#' reflective("Image",          multi_items("IMAG", 1:5)),
#'   reflective("Expectation",  multi_items("CUEX", 1:3)),
#'   reflective("Quality",      multi_items("PERQ", 1:7))
#' )
#'
#' #seminr syntax for freeing up item-item covariances
#' mobi_am <- associations(
#'              item_errors(c("PERQ1", "PERQ2"), "CUEX3"),
#'              item_errors("IMAG1", "CUEX2")
#'            )
#'
#' mobi_cfa <- estimate_cfa(mobi, mobi_mm, mobi_am)
#' @export
estimate_cfa <- function(data, measurement_model, item_associations=NULL, estimator="MLR", ...) {
  cat("Generating the seminr model for CFA\n")

  # TODO: see if fiml and other imputations work
  # data <- stats::na.omit(data)

  # TODO: consider higher order models (see estimate_pls() function for template)

  # TODO: warning if the model is incorrectly specified
  # warnings(measurement_model, data, structural_model)

  # Create LAVAAN syntax
  mmMatrix <- mm2matrix(measurement_model)
  measurement_syntax <- lavaan_mm_syntax(mmMatrix)
  association_syntax <- lavaan_item_associations(item_associations)

  full_syntax <- paste(measurement_syntax,
                       association_syntax,
                       sep="\n\n")

  # Run the model in LAVAAN
  library(lavaan)
  lavaan_model <- cfa(model=full_syntax, data=data, std.lv = TRUE,
                      estimator=estimator, ...)

  # Gather model information
  seminr_model <- list(
    data = data,
    measurement_model = measurement_model,
    # TODO: get construct names out of a measurement model
    # constructs = construct_names(structural_model),
    syntax = full_syntax,
    lavaan_model = lavaan_model
  )

  class(seminr_model) <- c("cfa_model", "seminr_model")
  return(seminr_model)
}

