#' seminr estimate_model Function
#'
#' The \code{seminr} package provides a natural syntax for researchers to describe PLS
#' structural equation models. \code{seminr} is compatible with semPLS, simplePLS and matrixPLS,
#' meaning that once a model is specified, it can be used across models for comparison.
#' \code{estimate_model} provides the verb for estimating a pls model from the plsm object
#' generated by \code{create_model}.
#'
#' @param seminr_model A \code{plsm} object generated by the \code{create_model} function
#'
#' @param ... A list of parameters inherited from the estimation function (default is semPLS)
#'
#' @param nboot Number of bootstrap iterations to perform. Default value is 0. If 0 then no
#'        bootstrapping is performed.
#'
#' @usage
#' estimate_model(seminr_model, ...)
#'
#' @seealso \code{\link{structure}} \code{\link{measure}} \code{\link{paths}} \code{\link{interact}}
#'          \code{\link{_createmodel}}
#'
#' @examples
#' data("mobi", package = "semPLS")
#'
#' #seminr syntax for creating measurement model
#' mobi_mm <- measure(
#'              reflect("Image",        multi_items("IMAG", 1:5)),
#'              reflect("Expectation",  multi_items("CUEX", 1:3)),
#'              reflect("Quality",      multi_items("PERQ", 1:7)),
#'              reflect("Value",        multi_items("PERV", 1:2)),
#'              reflect("Satisfaction", multi_items("CUSA", 1:3)),
#'              reflect("Complaints",   single_item("CUSCO")),
#'              reflect("Loyalty",      multi_items("CUSL", 1:3))
#'            )
#' #seminr syntax for creating structural model
#' mobi_sm <- structure(
#'   paths(from = "Image",        to = c("Expectation", "Satisfaction", "Loyalty")),
#'   paths(from = "Expectation",  to = c("Quality", "Value", "Satisfaction")),
#'   paths(from = "Quality",      to = c("Value", "Satisfaction")),
#'   paths(from = "Value",        to = c("Satisfaction")),
#'   paths(from = "Satisfaction", to = c("Complaints", "Loyalty")),
#'   paths(from = "Complaints",   to = "Loyalty")
#' )
#'
#' plsm_model <- create_model(data = mobi,
#'                            measurement_model = mobi_mm,
#'                            structural_model = mobi_sm)
#'
#' # Estimate model without bootstrapped significance
#' mobi_pls <- estimate_model(plsm_model)
#'
#' # Estimate model with bootstrapped significance
#' mobi_pls <- estimate_model(plsm_model, nboot = 200)
#'
#' print_paths(mobi_pls)
#' plot_scores(mobi_pls)
#' @export
estimate_model <- function(seminr_model, nboot = 0, ...) {
  cat("Estimating model using semPLS::sempls...\n")
  data <- seminr_model$data
  if (nboot > 0) {
    sempls_model <- semPLS::sempls(seminr_model, data, ...)
    mobi_pls_fitted <- semPLS::sempls(seminr_model, data, ...)

    # Initialize the Estimates Matrix
    bootstrapMatrix <- semPLS::sempls(seminr_model, data,...)$coefficients

    # Function to generate random samples with replacement
    getRandomIndex <- function(d) {return(sample.int(nrow(d),replace = TRUE))}
    # Function to get PLS estimate results
    getEstimateResults <- function(d) {
      return(semPLS::sempls(seminr_model, d[getRandomIndex(d),],...)$coefficients[,2])
    }

    # Bootstrap the estimates
    bootmatrix <- replicate(nboot,getEstimateResults(seminr_model$data))

    # Add the columns for bootstrap mean and standard error
    bootstrapMatrix <- cbind(bootstrapMatrix,apply(bootmatrix,1,mean))
    bootstrapMatrix <- cbind(bootstrapMatrix,apply(bootmatrix,1,sd))

    # Clean the column names
    colnames(bootstrapMatrix) <- c("Path","Estimate", "Bootstrapped Estimate","Standard Error")

    # Add the bootstrap matrix to the sempls object
    mobi_pls_fitted$bootstrapMatrix <- bootstrapMatrix


  } else {
    mobi_pls_fitted <- semPLS::sempls(seminr_model, data, ...)
  }
  return(mobi_pls_fitted)
}
