#' seminr estimate_cbsem() function
#'
#' The \code{seminr} package provides a natural syntax for researchers to describe
#' structural equation models.
#'
#' @param data A \code{dataframe} containing the indicator measurement data.
#'
#' @param measurement_model A source-to-target matrix representing the outer/measurement model,
#'   generated by \code{constructs}. Note that only reflective constructs are supported.
#'
#' @param structural_model A source-to-target matrix representing the inner/structural model,
#'   generated by \code{relationships}.
#'
#' @usage
#' estimate_cbsem(data, measurement_model, structural_model)
#'
#' @seealso \code{\link{as.reflective}} \code{\link{all.reflective}}
#'          \code{\link{relationships}} \code{\link{constructs}}
#'          \code{\link{paths}} \code{\link{interaction_term}}
#'          \code{\link{bootstrap_model}}
#'
#' @examples
#' mobi <- mobi
#'
#' #seminr syntax for creating measurement model
#' mobi_mm <- constructs(
#'              reflective("Image",        multi_items("IMAG", 1:5)),
#'              reflective("Expectation",  multi_items("CUEX", 1:3)),
#'              reflective("Quality",      multi_items("PERQ", 1:7)),
#'              reflective("Value",        multi_items("PERV", 1:2)),
#'              reflective("Satisfaction", multi_items("CUSA", 1:3)),
#'              reflective("Complaints",   single_item("CUSCO")),
#'              reflective("Loyalty",      multi_items("CUSL", 1:3))
#'            )
#'
#' #seminr syntax for freeing up item-item covariances
#' mobi_am <- associations(
#'              item_errors(c("PERQ1", "PERQ2"), "CUEX3"),
#'              item_errors("IMAG1", "CUEX2")
#'            )
#'
#' #seminr syntax for creating structural model
#' mobi_sm <- relationships(
#'   paths(from = "Image",        to = c("Expectation", "Satisfaction", "Loyalty")),
#'   paths(from = "Expectation",  to = c("Quality", "Value", "Satisfaction")),
#'   paths(from = "Quality",      to = c("Value", "Satisfaction")),
#'   paths(from = "Value",        to = c("Satisfaction")),
#'   paths(from = "Satisfaction", to = c("Complaints", "Loyalty")),
#'   paths(from = "Complaints",   to = "Loyalty")
#' )
#'
#' # Estimate model and get results
#' cbsem <- estimate_cbsem(mobi, mobi_mm, mobi_sm, mobi_am)
#' cbsem$results
#' @export
estimate_cbsem <- function(data, measurement_model, structural_model, item_associations=NULL, ...) {
  cat("Generating the seminr model\n")

  # TODO: see if fiml and other imputations work
  data <- stats::na.omit(data)

  # TODO: consider higher order models (see estimate_pls() function for template)

  # TODO: process interactions limited to repeated measures and orthogonalization
  # post_interaction_object <- process_interactions(measurement_model, data, structural_model, inner_weights)
  # measurement_model <- post_interaction_object$measurement_model

  # TODO: warning if the model is incorrectly specified
  # warnings(measurement_model, data, structural_model)


  # Create LAVAAN syntax
  measurement_syntax <- mm_syntax(measurement_model)

  outcomes <- unique(structural_model[, "target"])
  regressions <- lapply(outcomes, FUN=lavaan_regression, smMatrix=structural_model)
  structural_syntax <- paste("# Regressions",
                             paste(regressions, collapse="\n"),
                             sep="\n")

  association_syntax <- lavaan_item_associations(item_associations)

  # Put all the parts together
  full_syntax <- paste(measurement_syntax, structural_syntax, association_syntax,
                       sep="\n\n")

  # Run the model in LAVAAN
  library(lavaan)
  lavaan_model <- sem(model=full_syntax, data=data, std.lv = TRUE, ...)
  results <- summary(lavaan_model, fit.measures=TRUE, rsq=TRUE, standardized=TRUE)

  # Gather model information
  seminr_model <- list(
    data = data,
    measurement_model = measurement_model,
    structural_model = structural_model,
    constructs = construct_names(structural_model),
    syntax = full_syntax,
    lavaan_model = lavaan_model,
    results = results
  )

  class(seminr_model) <- c("cbsem_model", "seminr_model")
  return(seminr_model)
}

#' @export
estimate_cfa <- function(data, measurement_model, item_associations=NULL, ...) {
  cat("Generating the seminr model\n")

  data <- stats::na.omit(data)

  # TODO: consider higher order models (see estimate_pls() function for template)

  # TODO: warning if the model is incorrectly specified
  # warnings(measurement_model, data, structural_model)

  # Create LAVAAN syntax
  measurement_syntax <- mm_syntax(measurement_model)
  association_syntax <- lavaan_item_associations(item_associations)

  full_syntax <- paste(measurement_syntax,
                       association_syntax,
                       sep="\n\n")

  # Run the model in LAVAAN
  library(lavaan)
  lavaan_model <- cfa(model=full_syntax, data=data, std.lv = TRUE, ...)
  lavaan_results <- summary(lavaan_model, fit.measures=TRUE, standardized=TRUE)

  # Gather model information
  seminr_model <- list(
    data = data,
    measurement_model = measurement_model,
    # TODO: get construct names out of a measurement model
    # constructs = construct_names(structural_model),
    syntax = full_syntax,
    lavaan_model = lavaan_model,
    lavaan_results = lavaan_results
  )

  class(seminr_model) <- c("cfa_model", "seminr_model")
  return(seminr_model)
}

lavaan_item_associations <- function(item_associations) {
  if (is.null(item_associations)) return(NULL)
  associaxns <- apply(item_associations, MARGIN=1, FUN=lavaan_association)
  association_syntax <- paste("# Residual Covariances",
                              paste(associaxns, collapse="\n"),
                              sep="\n")
}

mm_syntax <- function(measurement_model) {
  # Create measurement model syntax
  measurements <- lapply(measurement_model, FUN = lavaan_construct)
  paste("# Latent Variable Definitions",
        paste(measurements, collapse="\n"),
        sep="\n")
}

#' @export
summary.cbsem_model <- function(object, na.print=".", digits=3, ...) {
  stopifnot(inherits(object, "cbsem_model"))
  #TODO: we should set the package attribute to seminr rather than as class attribute
  stopifnot(inherits(object, "seminr_model"))

  fit <- fitMeasures(object$lavaan_model)
}
