#' Measurement functions
#'
#' \code{measure} creates the factors from measurement items by assigning the
#' relevant items to each factor and specifying reflective or formative (composite/causal) measurement models
#'
#' This function conveniently maps measurement items to factors using
#' root name, numbers, and affixes with explicit definition of formative
#' or reflective structure
#'
#' @param \code{vector} of latent variable measurement specifications, as generated by the \code{reflective()}, \code{causal()}, or \code{composite()}
#'
#' @usage
#'   measurement_model <- measure(
#'                          reflective("Satisfaction", multi_items("SAT", 1:3)),
#'                          composite("Reputation", multi_items("REP", 1:3)),
#'                          causal("Performance", c("ROE", "ROA"))
#'                        )
#'
#' @seealso See \code{\link{causal}}, \code{\link{composite}}, \code{\link{reflective}}, \code{\link{multi_items}}
#'   and \code{\link{single_item}}
#'
#' @examples
#'   mobi_mm <- measure(
#'     reflective("Image",        multi_items("IMAG", 1:5)),
#'     reflective("Expectation",  multi_items("CUEX", 1:3)),
#'     reflective("Quality",      multi_items("PERQ", 1:7)),
#'     reflective("Value",        multi_items("PERV", 1:2)),
#'     reflective("Satisfaction", multi_items("CUSA", 1:3)),
#'     reflective("Complaints",   single_item("CUSCO")),
#'     reflective("Loyalty",      multi_items("CUSL", 1:3))
#'   )
#' @export
measure <- function(...) {
  return(matrix(c(...), ncol = 3, byrow = TRUE,
                dimnames = list(NULL, c("latent", "measurement", "type"))))
}

#' @export
reflective <- function(construct_name, item_names) {
  construct_names <- rep(construct_name, length(item_names))
  return(c(rbind(construct_names, item_names, "R")))
}

#' @export
causal <- function(construct_name, item_names) {
  construct_names <- rep(construct_name, length(item_names))
  return(c(rbind(construct_names,item_names,"F")))
}

#' @export
composite <- function(construct_name, item_names) {
  construct_names <- rep(construct_name, length(item_names))
  return(c(rbind(construct_names,item_names,"C")))
}

# arguments:
#   item_name: root name of all items
#   item_numbers: vector of item numbers
#   ...: optional affix arguments
#     prefix: prefix before each item name
#     mid: insert between item name and numbers
#     suffix: suffix after each ite name
#
# e.g.> multi_items("item", 0:3, prefix="X_", mid=".", suffix="_")
#
#' @export
multi_items <- function(item_name, item_numbers, ...) {
  affix <- as.data.frame(list(...))
  paste(affix$prefix, item_name, affix$mid, item_numbers, affix$suffix, sep = "")
}

#' @export
single_item <- function(item) {
  return(item)
}
