

#' Generating graphviz code for a model object.
#'
#' @param model A model object generated from seminr (can be a PLS, PLSc, lavaan or a bootstrapped model).
#' @param use_outer_weights determines whether to use weights or factor loadings
#' @param title The title of the diagram
#' @param title_font the font to use in the title (default: "helvetica")
#' @param title_size the font size of the title (default: 24pt)
#' @param theme a seminr visualization theme. Generated by the create_theme method
#'
#' @return A graphviz text that can be rendered using the DiagrammeR package
#' @export
#'
#' @examples
#' mobi <- mobi
#'
#' #seminr syntax for creating measurement model
#' mobi_mm <- constructs(
#'              reflective("Image",        multi_items("IMAG", 1:5)),
#'              reflective("Expectation",  multi_items("CUEX", 1:3)),
#'              reflective("Quality",      multi_items("PERQ", 1:7)),
#'              reflective("Value",        multi_items("PERV", 1:2)),
#'              reflective("Satisfaction", multi_items("CUSA", 1:3)),
#'              reflective("Complaints",   single_item("CUSCO")),
#'              reflective("Loyalty",      multi_items("CUSL", 1:3))
#'            )
#' #seminr syntax for creating structural model
#' mobi_sm <- relationships(
#'   paths(from = "Image",        to = c("Expectation", "Satisfaction", "Loyalty")),
#'   paths(from = "Expectation",  to = c("Quality", "Value", "Satisfaction")),
#'   paths(from = "Quality",      to = c("Value", "Satisfaction")),
#'   paths(from = "Value",        to = c("Satisfaction")),
#'   paths(from = "Satisfaction", to = c("Complaints", "Loyalty")),
#'   paths(from = "Complaints",   to = "Loyalty")
#' )
#'
#' mobi_pls <- estimate_pls(data = mobi,
#'                          measurement_model = mobi_mm,
#'                          structural_model = mobi_sm)
#'
#' plot_model(mobi_pls)
plot_model <- function(model, use_outer_weights = FALSE,
                       title = "",
                       title_font = "helvetica",
                       title_size = 24,
                       theme = create_theme()
){

  sm_nodes <- getSMnodes(model)
  mm_nodes <- getMMnodes(model)
  sm_edges <- getSMedges(model)
  mm_edges <- getMMedges(model, use_outer_weights = use_outer_weights)


  # TODO Refactor style function to genearte list object
  #      write function to convert list objects to dot-string
  #      extract font sizes to update theme widths + heights
  model$constructs %>% strwidth(.,font = 9, units = "in") %>% max()


  # use rank=same; A; B; C; to force same level on items of construct.

  glue::glue(
    "digraph G {{
      // general graph settings
      graph [
        charset = 'UTF-8',
        layout = dot,
        label = '{title}',
        fontsize = {title_size},
        fontname = {title_font},
        rankdir = LR,
        labelloc = t,
        //splines = false
      ]

      // The structural model
      subgraph sm {{
        rankdir = LR;
        node [
          {theme$construct_style}
        ]
        {sm_nodes}

        // How constructs are connected
        edge [
        {theme$inner_weight_style}
        ]
        {sm_edges}
      }

      // ---------------------
      // The measurement model
      // ---------------------
      subgraph mm {{
        node [
          {theme$item_style}
        ]
        {mm_nodes}

        // How items are connected with nodes
        edge [
        {theme$outer_weight_style}
        ]
        {mm_edges}
      }
  }"
  )
}



#
getFormattedNode <- function(construct, model, adjusted = FALSE, rounding = 3){

  rs <- ""
  if (construct %in% (model$rSquared %>% colnames() )) {
    rs <- paste0(construct, " [label='", construct,
                 "\nr²=", round(model$rSquared[1,construct],rounding),
                 "']")
  } else {
    rs <- paste0(construct)
  }
  rs
}

# gets structural nodes description
getSMnodes <- function(model, adjusted = FALSE, rounding = 3) {
  model$constructs %>%
    stringr::str_replace("\\*", "_x_") %>%
    sapply(., getFormattedNode, model, adjusted, rounding) %>%
    paste0(collapse = "\n")
}


# gets measurement nodes description
getMMnodes <- function(model) {
  model$mmVariables %>%
    dplyr::as_tibble() %>%
    dplyr::filter(!stringr::str_detect(value, "\\*")) %>%
    dplyr::pull(value) %>%
    #str_replace("\\*", "_x_") %>%
    paste0(collapse = "; ")
}



# get edges for structural model
getSMedges <- function(model, weights = 1, rounding = 3) {
  if ("boot_seminr_model" %in% class(model)) {
    cat("Using a bootstrapped PLS model\n")
    model$paths_descriptives
  } else {
    cat("Using an estimated PLS model\n")
  }

  nr <- nrow(model$smMatrix)
  nc <- ncol(model$smMatrix)
  sm <- model$smMatrix
  model$path_coef
  sm_edges <- ""

  for (i in 1:nrow(sm)) {
    #print(sm[i,1])
    coef <- round(model$path_coef[sm[i, 1], sm[i,2]], rounding)
    sm_edges <- paste0(sm_edges, sm[i, 1], " -> {", sm[i,2], "} [weight = ", weights, ", label = '𝞫=", coef, "', penwidth = ", coef * 5,"]\n")
  }
  sm_edges %>% stringr::str_replace_all("\\*", "_x_")
}


# get edges for measurement model
# weights for dot (high value recommended for mm)
getMMedges <- function(model, weights = 1000, rounding = 3, use_outer_weights = FALSE) {
  mm <- model$mmMatrix
  #%>% as_tibble()
  #mm <- mm %>% filter(!str_detect(measurement, "\\*")) %>%
  mm_edges <- ""

  # use_outer_weights <- FALSE
  for (i in 1:nrow(mm)) {
    # i <- 1
    if (use_outer_weights) {
      loading = round(model$outer_weights[mm[i,2], mm[i, 1]], rounding)
    } else {
      loading = round(model$outer_loadings[mm[i,2], mm[i, 1]], rounding)
    }
    if (stringr::str_detect(mm[i, 2], "\\*")) {
      # show interaction indicators?
    } else {
      mm_edges <- paste0(mm_edges, mm[i, 2], " -> {", mm[i,1], "} [weight = ",weights, ", label = ", loading ,", penwidth = ", loading * 3,"]\n")
    }
  }
  mm_edges %>% stringr::str_replace_all("\\*", "_x_")
}


if (FALSE) {

  model <- bs_model
  getSMedges(pls_model)
  getSMedges(bs_model)

  getSMedges(pls_model) %>% cat()
  getSMedges(bs_model) %>% cat()
  getMMedges(bs_model, rounding = 3) %>% cat()
}





createEdgeStyle <- function(color = "black", fontsize = 7, fontname = "helvetica", forward = TRUE, minlen = NA){

  arrowdir <-
    "dir = both,
     arrowhead = none,
     arrowtail = normal"

  if (forward) {
    arrowdir <-
      "dir = both,
     arrowhead = normal,
     arrowtail = none"
  }

  minlen_str <- ""
  if (!is.na(minlen)) {
    minlen_str <- glue::glue("minlen = {minlen},")
  }

  glue::glue("
             color = {color},
             fontsize = {fontsize},
             fontname = {fontname},
              {minlen_str}
              {arrowdir}
             ")
}

createOuterWeightStyle <- function(color = "dimgray", fontsize = 7, forward = FALSE, minlen = 1){
  createEdgeStyle(color = color,
                  fontsize = fontsize,
                  forward = forward, minlen = minlen)
}

createInnerWeightStyle <- function(color = "black", fontsize = 9, forward = TRUE){
  createEdgeStyle(color = color, fontsize = fontsize, forward = forward)
}



createItemStyle <- function(color = "dimgray", fill = "white", fontsize = 8, height = 0.2, width = 0.4){
  createStyle(shape = "box",
              color = color,
              fontsize = fontsize,
              fill = fill,
              width = width,
              height = height)
}

createConstructStyle <- function(color = "black", fill = "white", fontsize = 12, height = 0.5, width = 1){
  createStyle(shape = "ellipse",
              color = color,
              fill = fill,
              fontsize = fontsize,
              width = width,
              height = height)
}

createStyle <- function(shape = "box", color = "dimgray", fill = "white", fontsize = 8, height = 0.2, width = 0.4, fontname = "helvetica"){
  style <- glue::glue("
              shape = {shape},
              color = {color},
              fillcolor = {fill},
              style = filled,
              fontsize = {fontsize},
              height = {height},
              width = {width},
              fontname = {fontname},
              fixedsize = true
        ")
  style

}



create_theme <- function(item_style = createItemStyle(),
                         construct_style = createConstructStyle(),
                         outer_weight_style = createOuterWeightStyle(),
                         inner_weight_style = createInnerWeightStyle()) {
  list(item_style = item_style,
       construct_style = construct_style,
       outer_weight_style = outer_weight_style,
       inner_weight_style = inner_weight_style)
}





