#' Generating graphviz code for a model object.
#'
#' @param model A model object generated from seminr (can be a PLS, PLSc, lavaan or a bootstrapped model).
#' @param title The title of the diagram
#' @param title_font the font to use in the title (default: "helvetica")
#' @param title_size the font size of the title (default: 24pt)
#' @param theme a seminr visualization theme. Generated by the \code{create_theme} method
#'
#' @return A graphviz text that can be rendered using the DiagrammeR package
#' @export
#'
#' @examples
#' \dontrun{
#' mobi <- mobi
#'
#' #seminr syntax for creating measurement model
#' mobi_mm <- constructs(
#'              reflective("Image",        multi_items("IMAG", 1:5)),
#'              reflective("Expectation",  multi_items("CUEX", 1:3)),
#'              reflective("Quality",      multi_items("PERQ", 1:7)),
#'              reflective("Value",        multi_items("PERV", 1:2)),
#'              reflective("Satisfaction", multi_items("CUSA", 1:3)),
#'              reflective("Complaints",   single_item("CUSCO")),
#'              reflective("Loyalty",      multi_items("CUSL", 1:3))
#'            )
#' #seminr syntax for creating structural model
#' mobi_sm <- relationships(
#'   paths(from = "Image",        to = c("Expectation", "Satisfaction", "Loyalty")),
#'   paths(from = "Expectation",  to = c("Quality", "Value", "Satisfaction")),
#'   paths(from = "Quality",      to = c("Value", "Satisfaction")),
#'   paths(from = "Value",        to = c("Satisfaction")),
#'   paths(from = "Satisfaction", to = c("Complaints", "Loyalty")),
#'   paths(from = "Complaints",   to = "Loyalty")
#' )
#'
#' mobi_pls <- estimate_pls(data = mobi,
#'                          measurement_model = mobi_mm,
#'                          structural_model = mobi_sm)
#'
#' plot_model(mobi_pls)
#' }
plot_model <- function(model,
                       title = "",
                       title_font = "helvetica",
                       title_size = 24,
                       theme = create_theme()
){

  warning("This function is deprecated.")
  sm_nodes <- getSMnodes(model)
  mm_nodes <- getMMnodes(model)
  sm_edges <- getSMedges(model)
  mm_edges <- getMMedges(model)


  # todo:
  # use rank=same; A; B; C; to force same level on items of construct.

  glue::glue(
    "digraph G {{
      // general graph settings
      graph [
        charset = 'UTF-8',
        layout = dot,
        label = '{title}',
        fontsize = {title_size},
        fontname = {title_font},
        rankdir = LR,
        labelloc = t,
        //splines = false
      ]

      // The structural model
      subgraph sm {{
        rankdir = LR;
        node [
          {theme$construct_style}
        ]
        {sm_nodes}

        // How constructs are connected
        edge [
        {theme$inner_weight_style}
        ]
        {sm_edges}
      }

      // ---------------------
      // The measurement model
      // ---------------------
      subgraph mm {{
        node [
          {theme$item_style}
        ]
        {mm_nodes}

        // How items are connected with nodes
        edge [
        {theme$outer_weight_style}
        ]
        {mm_edges}
      }
  }"
  )
}






if (FALSE) {

  model <- bs_model
  getSMedges(pls_model)
  getSMedges(bs_model)

  getSMedges(pls_model) %>% cat()
  getSMedges(bs_model) %>% cat()
  getMMedges(bs_model, rounding = 3) %>% cat()
}



## OLD THEME ----

#' Creates a style definition for edges
#'
#' @param color Color of edge
#' @param fontsize Size of the text
#' @param fontname Font-type
#' @param forward direction of arrow
#' @param minlen minimal length of line
#'
#' @return dot-String for styling edges
#' @export
#'
# @examples
createEdgeStyle <- function(color = "black", fontsize = 7, fontname = "helvetica", forward = TRUE, minlen = NA){



  minlen_str <- ""
  if (!is.na(minlen)) {
    minlen_str <- glue::glue("minlen = {minlen},")
  }

  glue::glue("
             color = {color},
             fontsize = {fontsize},
             fontname = {fontname},
              {minlen_str}
             ")
}


#' Function to determine the edges for a measurement model
#'
#' @param color color of edge
#' @param fontsize Size of text
#' @param forward direction of arrow
#' @param minlen minimal length of arrow
#'
#' @return dot-string for styling edges
#' @export
#'
# @examples
createOuterWeightStyle <- function(color = "dimgray", fontsize = 7, forward = FALSE, minlen = 1){
  createEdgeStyle(color = color,
                  fontsize = fontsize,
                  forward = forward, minlen = minlen)
}


#' Function to determine the edges for a structural model
#'
#' @param color color of edge
#' @param fontsize Size of text
#' @param forward direction of arrow
#'
#' @return dot-string for styling edges
#' @export
#'
# @examples
createInnerWeightStyle <- function(color = "black", fontsize = 9, forward = TRUE){
  createEdgeStyle(color = color, fontsize = fontsize, forward = forward)
}


#' Creates a style definition for measurement items
#'
#' @param color Color of node
#' @param fill fill of the node
#' @param fontsize Size of the text
#' @param height the height of the node
#' @param width the width of the node
#'
#' @return dot-String for styling nodes
#' @export
#'
# @examples
createItemStyle <- function(color = "dimgray", fill = "white", fontsize = 8, height = 0.2, width = 0.4){
  createStyle(shape = "box",
              color = color,
              fontsize = fontsize,
              fill = fill,
              width = width,
              height = height)
}

#' Creates a style definition for measurement constructs
#'
#' @param color Color of node
#' @param fill fill of the node
#' @param fontsize Size of the text
#' @param height the height of the node
#' @param width the width of the node
#'
#' @return dot-String for styling nodes
#' @export
#'
# @examples
createConstructStyle <- function(color = "black", fill = "white", fontsize = 12, height = 0.5, width = 1){
  createStyle(shape = "ellipse",
              color = color,
              fill = fill,
              fontsize = fontsize,
              width = width,
              height = height)
}

#' Creates a style definition for nodes
#'
#' @param shape the shape for the node
#' @param color Color of node
#' @param fill fill of the node
#' @param fontsize Size of the text
#' @param height the height of the node
#' @param width the width of the node
#' @param fontname Font-type
#'
#' @return dot-String for styling nodes
#' @export
#'
# @examples
createStyle <- function(shape = "box", color = "dimgray", fill = "white", fontsize = 8, height = 0.2, width = 0.4, fontname = "helvetica"){
  style <- glue::glue("
              shape = {shape},
              color = {color},
              fillcolor = {fill},
              style = filled,
              fontsize = {fontsize},
              height = {height},
              width = {width},
              fontname = {fontname},
              fixedsize = true
        ")
  style

}



#' Factory for creating a theme object
#'
#' @param item_style the dot-style for an item
#' @param construct_style the dot-style for a construct
#' @param outer_weight_style the dot-style for the measurement model
#' @param inner_weight_style the dot-style for the structural model
#'
#' @return a theme object used in the plot_model function
#' @export
#'
# @examples
create_theme <- function(item_style = createItemStyle(),
                         construct_style = createConstructStyle(),
                         outer_weight_style = createOuterWeightStyle(),
                         inner_weight_style = createInnerWeightStyle()) {
  list(item_style = item_style,
       construct_style = construct_style,
       outer_weight_style = outer_weight_style,
       inner_weight_style = inner_weight_style)
}


